# Generated by Django 5.0.2 on 2024-02-14 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_briefing_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='retailer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retailers', to='api.retailer'),
        ),
    ]
